package main

import (
	"fmt"
	"os"

	"grammar-validator/parser"

	"github.com/antlr4-go/antlr/v4"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <file.vx> [file2.vx ...]\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "\nValidates Vex grammar by parsing .vx files using generated ANTLR parser\n")
		fmt.Fprintf(os.Stderr, "\nNote: This tool requires generated Vex parser files to be present.\n")
		fmt.Fprintf(os.Stderr, "Run 'antlr4 -Dlanguage=Go -listener -visitor Vex.g4 -o .' first.\n")
		os.Exit(1)
	}

	// Check if parser files exist
	if !filesExist("parser/vex_lexer.go", "parser/vex_parser.go") {
		fmt.Fprintf(os.Stderr, "❌ Generated Vex parser files not found.\n")
		fmt.Fprintf(os.Stderr, "This tool needs parser/vex_lexer.go and parser/vex_parser.go to be present.\n")
		fmt.Fprintf(os.Stderr, "These are generated by ANTLR from the Vex.g4 grammar file.\n")
		os.Exit(1)
	}

	var failedFiles []string

	for _, filename := range os.Args[1:] {
		fmt.Printf("\nTesting: %s\n", filename)

		// Read file content
		content, err := os.ReadFile(filename)
		if err != nil {
			fmt.Printf("❌ Failed to read %s: %v\n", filename, err)
			failedFiles = append(failedFiles, filename)
			continue
		}

		// Create input stream
		inputStream := antlr.NewInputStream(string(content))

		// Create lexer
		lexer := parser.NewVexLexer(inputStream)

		// Create token stream
		tokenStream := antlr.NewCommonTokenStream(lexer, 0)

		// Create parser
		vexParser := parser.NewVexParser(tokenStream)

		// Add error listener to catch syntax errors
		errorListener := &ErrorListener{filename: filename}
		vexParser.RemoveErrorListeners()
		vexParser.AddErrorListener(errorListener)

		// Parse starting from the 'sp' rule (root rule)  
		tree := vexParser.Sp()

		if errorListener.hasError {
			failedFiles = append(failedFiles, filename)
		} else {
			fmt.Printf("✅ %s parsed successfully\n", filename)
			fmt.Printf("Parse tree: %s\n", tree.ToStringTree(vexParser.GetRuleNames(), vexParser))
		}
	}

	if len(failedFiles) > 0 {
		fmt.Println("\n💥 The following files failed to parse:")
		for _, file := range failedFiles {
			fmt.Printf("  - %s\n", file)
		}
		os.Exit(1)
	} else {
		fmt.Println("\n🎉 All .vx example files parsed successfully!")
	}
}

// ErrorListener captures syntax errors
type ErrorListener struct {
	*antlr.DefaultErrorListener
	filename string
	hasError bool
}

func (el *ErrorListener) SyntaxError(recognizer antlr.Recognizer, offendingSymbol interface{}, line, column int, msg string, e antlr.RecognitionException) {
	fmt.Printf("❌ Syntax error in %s at line %d:%d - %s\n", el.filename, line, column, msg)
	el.hasError = true
}

func filesExist(files ...string) bool {
	for _, file := range files {
		if _, err := os.Stat(file); err != nil {
			return false
		}
	}
	return true
}