name: Stdlib Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

env:
  GO_VERSION: '1.21'
  ANTLR_VERSION: '4.13.1'

jobs:
  # Detect changes in stdlib files and related testing infrastructure
  # This workflow only runs when stdlib-specific files change, not on every commit
  detect-stdlib-changes:
    runs-on: ubuntu-latest
    outputs:
      stdlib-changed: ${{ steps.changes.outputs.stdlib-files || 'false' }}
      has-changes: ${{ steps.changes.outputs.has-changes || 'false' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Detect stdlib and testing infrastructure changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          stdlib-files:
            - 'stdlib/**/*.vx'
            - 'stdlib/**/*.vex'
            - 'stdlib/**/*.md'
            - '.github/scripts/test/run-tests.sh'
            - '.github/workflows/stdlib-tests.yml'
          has-changes:
            - '**'

  # Run stdlib tests
  stdlib-tests:
    runs-on: ubuntu-latest
    needs: [detect-stdlib-changes]
    if: needs.detect-stdlib-changes.outputs.stdlib-changed == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        
    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-
          
    # Cache ANTLR installation
    - name: Cache ANTLR
      id: antlr-cache
      uses: actions/cache@v4
      with:
        path: /usr/local/lib/antlr.jar
        key: ${{ runner.os }}-antlr-${{ env.ANTLR_VERSION }}
        
    - name: Install ANTLR
      if: steps.antlr-cache.outputs.cache-hit != 'true'
      env:
        ANTLR_VERSION: ${{ env.ANTLR_VERSION }}
      run: .github/scripts/build/install-antlr.sh
        
    - name: Setup ANTLR binary
      run: .github/scripts/build/setup-antlr-binary.sh
        
    - name: Install Go dependencies
      run: .github/scripts/utils/install-go-deps.sh
        
    # Cache parser generation
    - name: Cache generated parsers
      id: parser-cache
      uses: actions/cache@v4
      with:
        path: tools/gen/
        key: ${{ runner.os }}-parser-${{ hashFiles('tools/grammar/**') }}
        
    - name: Generate parsers
      if: steps.parser-cache.outputs.cache-hit != 'true'
      run: .github/scripts/build/generate-parsers.sh
        
    - name: Build Vex transpiler
      run: .github/scripts/build/build-project.sh

    - name: Run stdlib tests
      id: stdlib-tests
      run: .github/scripts/test/run-tests.sh


  # Skip job when no stdlib changes
  stdlib-tests-skip:
    runs-on: ubuntu-latest
    needs: [detect-stdlib-changes]
    if: needs.detect-stdlib-changes.outputs.stdlib-changed == 'false'
    steps:
    - name: Skip stdlib tests
      run: |
        echo "⏭️ Skipping stdlib tests - no relevant changes detected"
        echo "📁 Monitored paths:"
        echo "   - stdlib/**/*.vx (stdlib source files)"
        echo "   - stdlib/**/*.vex (stdlib source files)"
        echo "   - stdlib/**/*.md (stdlib documentation)"
        echo "   - .github/scripts/test/run-tests.sh (testing script)"
        echo "   - .github/workflows/stdlib-tests.yml (this workflow)"
        echo ""
        echo "💡 Stdlib tests will run when any of these files change"
        echo "🔄 Overall changes detected: ${{ needs.detect-stdlib-changes.outputs.has-changes }}"
